### ISSUE TITLE
Is chmod 666 safe for /dev/kvm?

### ISSUE THREAD

**Issue by lostinblue** [stefwalter/oci-kvm-hook#2]
Those permissions seem very lax, that appears like it could be dangerous

**Comment by stefwalter** [comment]
Unfortunately this is one of those things it seems nobody can agree on. Qemu and Libvirt as packaged by Red Hat make this happen by default. I'm sure this is a good discussion, but in this case I'll follow suit rather than make decisions here.

```
# ls -l /dev/kvm
crw-rw-rw-. 1 root kvm 10, 232 Jul 14 07:49 /dev/kvm
# cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
```

Perhaps oci-kvm-hook should just copy the permissions from the host?

**Comment by stefwalter** [comment]
I've merged a change which copies the permissions from the host. This makes oci-kvm-hook match the admin's and/or linux distribution's policy.
